spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asset_management
    username: root
    password: nclc123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true